### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [qnopka/grid-template#1]
1)
шрифт не соответствует макету
![image](https://user-images.githubusercontent.com/8464662/95505001-474f2880-09b6-11eb-9dc7-df3df5d2841b.png)

2)
проблемы с положением меню
![image](https://user-images.githubusercontent.com/8464662/95505099-7796c700-09b6-11eb-905d-4eee57789989.png)

3)
требования к размеру ячеек не выполнены
![image](https://user-images.githubusercontent.com/8464662/95505145-8ed5b480-09b6-11eb-83cb-f8cfe28e60df.png)

**Comment by qnopka** [comment]
добрый день, ошибки исправила

https://github.com/qnopka/grid-template.git
https://qnopka.github.io/grid-template/

**Comment by Alecto** [comment]
отлично.
работа принята.
напомните группу и фио, а то при переписке через гитхаб все потерялось ) не
могу найти qnopka ))

пт, 9 жовт. 2020 о 11:38 qnopka <notifications@github.com> пише:
